# Generated by Django 5.1.4 on 2025-01-13 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('3rd_gender', '3rd Gender')], max_length=20)),
                ('weight_kg', models.FloatField()),
                ('height_feet', models.PositiveIntegerField(null=True)),
                ('height_remaining_inches', models.PositiveIntegerField(null=True)),
                ('age', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmi_index', models.CharField(blank=True, choices=[('excessive_underweight', 'Excessive underweight'), ('underweight', 'Underweight'), ('normal_underweight', 'Normal weight'), ('overweight', 'Overweight'), ('obese', 'Obese'), ('severely_obese', 'Severely obese')], max_length=30, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmi', to='patient.patient')),
            ],
        ),
    ]
