# Generated by Django 5.1.4 on 2025-01-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('medicine', models.ManyToManyField(blank=True, related_name='category', to='medicine.medicine')),
            ],
        ),
    ]
