# Generated by Django 5.1.4 on 2025-01-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ManyToManyField(blank=True, null=True, related_name='wish_list', to='medicine.medicine')),
            ],
        ),
    ]
