# Generated by Django 5.1.4 on 2025-01-14 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '__first__'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ManyToManyField(blank=True, related_name='wish_list', to='medicine.medicine')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='patient.patient')),
            ],
        ),
    ]
