# Generated by Django 5.1.4 on 2025-01-14 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='patient',
        ),
    ]
