# Generated by Django 5.1.4 on 2025-01-14 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultASpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_name', models.CharField(max_length=50)),
                ('consultation_fee', models.FloatField()),
                ('vat_percent', models.PositiveIntegerField()),
                ('platform_fee', models.PositiveIntegerField()),
                ('net_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('vat_in_taka', models.FloatField(blank=True, null=True)),
                ('promo_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consult_a_specialist', to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_a_specialist', to='patient.patient')),
            ],
        ),
    ]
