# Generated by Django 5.1.4 on 2025-01-14 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_patient'),
        ('patient', '0001_initial'),
        ('wish_list', '0002_remove_wishlist_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='patient',
            name='wish_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='wish_list.wishlist'),
        ),
    ]
