# Generated by Django 5.1.4 on 2025-01-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
