# Generated by Django 5.1.4 on 2025-01-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('medicine', '0006_alter_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='medicine',
            field=models.ManyToManyField(related_name='carts', to='medicine.medicine'),
        ),
    ]
