# Generated by Django 5.1.4 on 2025-01-14 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('depertment', models.CharField(blank=True, max_length=200, null=True)),
                ('total_experience', models.IntegerField(blank=True, null=True)),
                ('doctor_type', models.CharField(blank=True, choices=[('medical', 'Medical'), ('dental', 'Dental'), ('veterinary', 'Veterinary')], max_length=30, null=True)),
                ('bmdc_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('3rd_gender', '3rd Gender')], max_length=10, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('area_thana', models.CharField(blank=True, max_length=100, null=True)),
                ('nid_passport_number', models.CharField(blank=True, max_length=18, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('instance_consultation_start_time', models.TimeField()),
                ('instance_consultation_end_time', models.TimeField()),
                ('instance_consultation_start_day', models.CharField(blank=True, choices=[('sat', 'Sat'), ('sun', 'Sun'), ('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri')], default='Sat', max_length=10, null=True)),
                ('instance_consultation_end_day', models.CharField(blank=True, choices=[('sat', 'Sat'), ('sun', 'Sun'), ('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri')], default='Fri', max_length=10, null=True)),
                ('apointment_consultation_start_time', models.TimeField()),
                ('apointment_consultation_end_time', models.TimeField()),
                ('apointment_consultation_start_day', models.CharField(blank=True, choices=[('sat', 'Sat'), ('sun', 'Sun'), ('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri')], default='Sat', max_length=10, null=True)),
                ('apointment_consultation_end_day', models.CharField(blank=True, choices=[('sat', 'Sat'), ('sun', 'Sun'), ('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri')], default='Fri', max_length=10, null=True)),
                ('consultation_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('follow_up_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('follow_up_fee_applicable_days', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_attended', models.PositiveIntegerField(blank=True, null=True)),
                ('joined_date_in_aracol_apps', models.DateTimeField(auto_now_add=True)),
                ('avg_consultation_time', models.PositiveIntegerField(blank=True, null=True)),
                ('doctor_code', models.CharField(blank=True, max_length=10, null=True)),
                ('about', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('super_admin', 'super_admin'), ('doctor', 'doctor')], default='doctor', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
