# Generated by Django 5.1.4 on 2025-01-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('super_admin', 'super_admin'), ('doctor', 'doctor')], default='doctor', max_length=20),
        ),
    ]
