# Generated by Django 5.1.4 on 2025-01-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_apointment_consultation_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='apointment_consultation_end_day',
            field=models.CharField(blank=True, choices=[('sat', 'Sat'), ('sun', 'Sun'), ('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri')], default='sri', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='apointment_consultation_start_day',
            field=models.CharField(blank=True, choices=[('sat', 'Sat'), ('sun', 'Sun'), ('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri')], default='sat', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='instance_consultation_end_day',
            field=models.CharField(blank=True, choices=[('sat', 'Sat'), ('sun', 'Sun'), ('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri')], default='sri', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='instance_consultation_start_day',
            field=models.CharField(blank=True, choices=[('sat', 'Sat'), ('sun', 'Sun'), ('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri')], default='sat', max_length=10, null=True),
        ),
    ]
