# Generated by Django 5.1.4 on 2025-01-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_specialist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialist',
            new_name='specialization',
        ),
    ]
