# Generated by Django 5.1.4 on 2025-01-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'home'), ('doctor', 'doctor')], default='home', max_length=10),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default='banner', max_length=100),
        ),
    ]
